name: Release

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  check-release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      id-token: write
    outputs:
      VERIFY_RELEASE_VERSION: ${{ steps.semantic.outputs.VERIFY_RELEASE_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Release template
        uses: ./.github/actions/release
        id: semantic
        with:
          app_id: ${{ secrets.PAT_APP_ID }}
          private_key: ${{ secrets.PAT_APP_PRIVATE_KEY }}
          npm_token: ${{ secrets.NPM_TOKEN }}
          args: --dry-run --no-ci

  release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: check-release
    if: needs.check-release.outputs.VERIFY_RELEASE_VERSION != ''
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Release template
        uses: ./.github/actions/release
        with:
          app_id: ${{ secrets.PAT_APP_ID }}
          private_key: ${{ secrets.PAT_APP_PRIVATE_KEY }}
          npm_token: ${{ secrets.NPM_TOKEN }}
