name: Release

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  check-release:
    runs-on: ubuntu-latest
    uses: ./.github/actions/release
    permissions:
      contents: read
      id-token: write
    with:
      args: --dry-run --no-ci
    secrets:
      pat_app_id: ${{ secrets.PAT_APP_ID }}
      pat_app_private_key: ${{ secrets.PAT_APP_PRIVATE_KEY }}

  release:
    runs-on: ubuntu-latest
    uses: ./.github/actions/release
    needs: check-release
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    secrets:
      pat_app_id: ${{ secrets.PAT_APP_ID }}
      pat_app_private_key: ${{ secrets.PAT_APP_PRIVATE_KEY }}
