name: Release

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  check-release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Use template
        uses: ./.github/actions/release
        with:
          app_id: ${{ secrets.PAT_APP_ID }}
          app_private_key: ${{ secrets.PAT_APP_PRIVATE_KEY }}
          args: --dry-run --no-ci

  release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: check-release
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Use template
        uses: ./.github/actions/release
        with:
          app_id: ${{ secrets.PAT_APP_ID }}
          app_private_key: ${{ secrets.PAT_APP_PRIVATE_KEY }}
